server:
  port: 4000

secret:
  key: 5tL8bu7gWhFn9sZpQdXDz4bEAJc1TKhtu2oM6qVfwNixGsZo9Km3npRyFS3D4JuHzms


spring:
#Mysql Config
  datasource:
    url: jdbc:mysql://localhost:3306/teampl
    username: teamPLDeveloper
    password: 882614
    driver-class-name: com.mysql.cj.jdbc.Driver
# Redis Config
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      lettuce:
        pool:
          max-wait: 500ms
          max-active: 10
          max-idle: 10
          min-idle: 10

  # SMTP Config
  mail:
    host: smtp.gmail.com
    port: 587
    username: jdj8812041@gmail.com
    password: nulg nzuk eroe phsz
    properties:
      mail:
        smtp:
          auth : true;
          starttls:
            enable : true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  #Sprign JPA Auto Query  Changer Off
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#Custom Thread Config
custom:
  thread-pool:
    core-pool-size: 50
    max-pool-size: 100
    queue-capacity: 100

#Web Token Expire Time
token:
  expire:
    auth-code-token: 300
    login-token: 10800
